// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh50nlIWdRmJFmOryG8knug35CbST4yqU',
    appId: '1:841829714069:web:e1031fb83595bf673b739c',
    messagingSenderId: '841829714069',
    projectId: 'anchorpoint-f7e77',
    authDomain: 'anchorpoint-f7e77.firebaseapp.com',
    storageBucket: 'anchorpoint-f7e77.firebasestorage.app',
    measurementId: 'G-8Z1NWNV5QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmp4QV52em1FbLtSYpg8coXoMnltZ2gXs',
    appId: '1:841829714069:android:b1ac91a70dc10d433b739c',
    messagingSenderId: '841829714069',
    projectId: 'anchorpoint-f7e77',
    storageBucket: 'anchorpoint-f7e77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo2td1jZvGtVw06FMEoQ0eR0VSy61QTUA',
    appId: '1:841829714069:ios:f7f736ba761cc2113b739c',
    messagingSenderId: '841829714069',
    projectId: 'anchorpoint-f7e77',
    storageBucket: 'anchorpoint-f7e77.firebasestorage.app',
    iosBundleId: 'com.example.anchorpoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo2td1jZvGtVw06FMEoQ0eR0VSy61QTUA',
    appId: '1:841829714069:ios:f7f736ba761cc2113b739c',
    messagingSenderId: '841829714069',
    projectId: 'anchorpoint-f7e77',
    storageBucket: 'anchorpoint-f7e77.firebasestorage.app',
    iosBundleId: 'com.example.anchorpoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh50nlIWdRmJFmOryG8knug35CbST4yqU',
    appId: '1:841829714069:web:fd5a35d21f1273113b739c',
    messagingSenderId: '841829714069',
    projectId: 'anchorpoint-f7e77',
    authDomain: 'anchorpoint-f7e77.firebaseapp.com',
    storageBucket: 'anchorpoint-f7e77.firebasestorage.app',
    measurementId: 'G-97CFNZE5SN',
  );
}
